package domain.dispatcher;

public enum AllowedAction {
    MEALPLANNER_ENTRY,
    GET_ALL_FOOD,
    GET_SINGLE_FOOD,
    CREATE_FOOD,
    SEARCH_FOOD,
    DISH_CREATE,
    DISH_GET_ALL,
    DISH_GET_SINGLE,
    DISH_INGREDIENT_ADD,
    DISH_INGREDIENT_UPDATE,
    DISH_INGREDIENT_REMOVE,
    USER_CREATE,
    USER_GET_ALL,
    USER_GET_SINGLE,
    USER_GET_BY_USERNAME,
    USER_GET_BY_EMAIL,
    USER_UPDATE,
    CART_CREATE,
    CART_GET,
    CART_ADD_DISH,
    CART_ADD_DISH_BY_USER,
    CART_SUMMARY
}
