quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.http.port=8081
quarkus.log.console.level=INFO

# H2 Web-Console (l√§uft am gleichen Port wie die App)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:mealplanner;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# H2 Web-Console (l‰uft am gleichen Port wie die App)
quarkus.datasource.h2.console.enabled=true
quarkus.datasource.h2.console.path=/h2-console
